// Mocks generated by Mockito 5.3.2 from annotations
// in elearning/test/update_profile_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:elearning/core/data/models/profile_model.dart' as _i4;
import 'package:elearning/core/data/models/user_model.dart' as _i5;
import 'package:elearning/core/data/repositories/account_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i2.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataProfileModel?> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i3.Future<_i4.DataProfileModel?>.value(),
      ) as _i3.Future<_i4.DataProfileModel?>);
  @override
  _i3.Future<_i5.DataResponseModel?> updateProfile(_i4.DataToUpdate? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i3.Future<_i5.DataResponseModel?>.value(),
      ) as _i3.Future<_i5.DataResponseModel?>);
  @override
  _i3.Future<_i5.DataResponseModel?> updatePassword(
    String? currentPassword,
    String? newPassword,
    String? newPasswordConfirmation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [
            currentPassword,
            newPassword,
            newPasswordConfirmation,
          ],
        ),
        returnValue: _i3.Future<_i5.DataResponseModel?>.value(),
      ) as _i3.Future<_i5.DataResponseModel?>);
}
